
setTimeout("document.bgColor = 'white'", 1000)
setTimeout("document.bgColor = 'lightpink'", 1500)
setTimeout("document.bgColor = 'pink'", 2000)
setTimeout("document.bgColor = 'darksalmon'", 2500)
setTimeout("document.bgColor = 'plum'", 3000)
setTimeout("document.bgColor = 'tomato'", 3500)
setTimeout("document.bgColor = 'peru'", 4000)
setTimeout("document.bgColor = 'cornsilk'", 4500)
setTimeout("document.bgColor = 'yellow'", 5000)
setTimeout("document.bgColor = 'rosybrown'", 5500)
setTimeout("document.bgColor = 'sandybrown'", 6000)
setTimeout("document.bgColor = 'white'", 1000)
setTimeout("document.bgColor = 'lightpink'", 1500)
setTimeout("document.bgColor = 'pink'", 2000)
setTimeout("document.bgColor = 'darksalmon'", 2500)
setTimeout("document.bgColor = 'plum'", 3000)
setTimeout("document.bgColor = 'tomato'", 3500)
setTimeout("document.bgColor = 'peru'", 4000)
setTimeout("document.bgColor = 'cornsilk'", 4500)
setTimeout("document.bgColor = 'yellow'", 5000)
setTimeout("document.bgColor = 'rosybrown'", 5500)
setTimeout("document.bgColor = 'sandybrown'", 6000)
setTimeout("document.bgColor = 'white'", 1000)
setTimeout("document.bgColor = 'lightpink'", 1500)
setTimeout("document.bgColor = 'pink'", 2000)
setTimeout("document.bgColor = 'darksalmon'", 2500)
setTimeout("document.bgColor = 'plum'", 3000)
setTimeout("document.bgColor = 'tomato'", 3500)
setTimeout("document.bgColor = 'peru'", 4000)
setTimeout("document.bgColor = 'cornsilk'", 4500)
setTimeout("document.bgColor = 'yellow'", 5000)
setTimeout("document.bgColor = 'rosybrown'", 5500)
setTimeout("document.bgColor = 'sandybrown'", 6000)
setTimeout("document.bgColor = 'white'", 1000)
setTimeout("document.bgColor = 'lightpink'", 1500)
setTimeout("document.bgColor = 'pink'", 2000)
setTimeout("document.bgColor = 'darksalmon'", 2500)
setTimeout("document.bgColor = 'plum'", 3000)
setTimeout("document.bgColor = 'tomato'", 3500)
setTimeout("document.bgColor = 'peru'", 4000)
setTimeout("document.bgColor = 'cornsilk'", 4500)
setTimeout("document.bgColor = 'yellow'", 5000)
setTimeout("document.bgColor = 'rosybrown'", 5500)
setTimeout("document.bgColor = 'sandybrown'", 6000)




